// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcyqPbUmEWrurknCIoD20t4rs8_NQukDo',
    appId: '1:66870036552:web:80276f8617a411b450707d',
    messagingSenderId: '66870036552',
    projectId: 'house-party-001',
    authDomain: 'house-party-001.firebaseapp.com',
    storageBucket: 'house-party-001.appspot.com',
    measurementId: 'G-31SM6MJ7T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAk_3sZftubHg0aOJl2n2yqTOgNnhfBzg',
    appId: '1:66870036552:android:6994ba9915785f1b50707d',
    messagingSenderId: '66870036552',
    projectId: 'house-party-001',
    storageBucket: 'house-party-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM0BYQaSp0eBtMmpAj_sKRbXt6ti6ysbc',
    appId: '1:66870036552:ios:347ef3385b5d23fc50707d',
    messagingSenderId: '66870036552',
    projectId: 'house-party-001',
    storageBucket: 'house-party-001.appspot.com',
    iosClientId: '66870036552-bulbl19pfclqn2uq3v14fhddic33qqtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM0BYQaSp0eBtMmpAj_sKRbXt6ti6ysbc',
    appId: '1:66870036552:ios:347ef3385b5d23fc50707d',
    messagingSenderId: '66870036552',
    projectId: 'house-party-001',
    storageBucket: 'house-party-001.appspot.com',
    iosClientId: '66870036552-bulbl19pfclqn2uq3v14fhddic33qqtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
